name: CI Lint and Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Execute lint
        run: npm run lint

      - name: Execute build
        run: npm run build
